<script setup lang="ts">
import { onMounted, ref } from 'vue'
import PageHeader from '@/components/common/PageHeader.vue'
import MetricCard from '@/components/common/MetricCard.vue'
import { auditService } from '@/services/admin'
import type { AuditEvent, Metrics } from '@/types/domain'
const metrics = ref<Metrics>({ questions_today: 0, positive_rate: 0, no_answer_rate: 0, citation_coverage: 0, documents_published: 0, sync_backlog: 0, delivery_success: 0 }); const events = ref<AuditEvent[]>([])
const actionLabels: Record<string, string> = { 'auth.login': '登录系统', 'knowledge.document.upload': '上传制度', 'knowledge.document.publish': '发布制度', 'knowledge.source.create': '连接资料源', 'knowledge.source.sync_requested': '触发同步', 'agent.profile.create': '创建 Agent', 'agent.profile.update': '更新 Agent 配置', 'notification.create': '创建通知', 'notification.approve': '审核通知', 'notification.send': '发送通知' }
onMounted(async () => { [metrics.value, events.value] = await Promise.all([auditService.metrics(), auditService.list()]) })
</script>
<template><section class="admin-page"><PageHeader eyebrow="QUALITY & COMPLIANCE" title="质量与审计" description="持续观察回答质量、知识覆盖和关键管理操作，所有指标都能追溯到配置版本。" /><div class="metric-grid"><MetricCard label="今日问答" :value="metrics.questions_today" note="员工制度咨询" /><MetricCard label="正向反馈" :value="`${Math.round(metrics.positive_rate * 100)}%`" note="员工评价" tone="green" /><MetricCard label="无依据回答" :value="`${Math.round(metrics.no_answer_rate * 100)}%`" note="严格拒答率" tone="amber" /><MetricCard label="引用覆盖" :value="`${Math.round(metrics.citation_coverage * 100)}%`" note="目标 100%" tone="violet" /></div><div class="audit-layout"><section class="quality-panel"><div class="section-heading"><div><h2>质量基线</h2><p>发布新配置前必须通过固定制度问题集。</p></div><el-tag type="success">当前达标</el-tag></div><div class="quality-bars"><div><span>引用覆盖率</span><el-progress :percentage="Math.round(metrics.citation_coverage * 100)" :stroke-width="9" /></div><div><span>通知送达率</span><el-progress :percentage="Math.round(metrics.delivery_success * 100)" :stroke-width="9" color="#22a06b" /></div><div><span>有依据回答率</span><el-progress :percentage="Math.round((1 - metrics.no_answer_rate) * 100)" :stroke-width="9" color="#7c3aed" /></div></div></section><section class="audit-log"><div class="section-heading"><div><h2>审计日志</h2><p>关键操作只追加、不覆盖。</p></div></div><div class="audit-events"><article v-for="event in events" :key="event.id"><span /><div><strong>{{ actionLabels[event.action] || event.action }}</strong><p>{{ event.actor_name }} · {{ event.resource_type }} · {{ event.resource_id }}</p></div><time>{{ new Date(event.created_at).toLocaleString('zh-CN') }}</time></article><el-empty v-if="!events.length" description="暂无审计事件" :image-size="80" /></div></section></div></section></template>
